### ISSUE TITLE
how to fix it? 

### ISSUE THREAD

**Issue by AlexJoz** [domdorn/glassfish4_embedded_cdi_bug#1]
WARNING: RAR7000 : Check for a new version of MQ installation failed : C:\Users\
Skazzi\AppData\Local\Temp\gfembed6749258839938920369tmp\lib\install\applications
\jmsra\..\imqjmsra.rar (The system cannot find the file specified):C:\Users\Skaz
zi\AppData\Local\Temp\gfembed6749258839938920369tmp\lib\install\applications\jms
ra\imqjmsra.rar
Nov 21, 2015 3:00:29 AM PluginUtil startGlassFish
INFO: Started GlassFish ServerId = maven, GlassFish = com.sun.enterprise.glassfi
sh.bootstrap.StaticGlassFishRuntime$1@16a35bd, TimeTaken = 2,205 ms
Nov 21, 2015 3:00:29 AM PluginUtil doDeploy
INFO: Deployed null
Hit ENTER to redeploy, X to exit  

glassfish is running, but play app not deployed =(

**Comment by domdorn** [comment]
forget play on glassfish... run it standalone

**Comment by AlexJoz** [comment]
lol thnx )) I will!

p.s. It was just a study task... and I made it btw ))
